<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-19T12:13:10 IST" name="Suite" finished-at="2024-07-19T12:13:20 IST" duration-ms="9764">
    <groups>
    </groups>
    <test started-at="2024-07-19T12:13:10 IST" name="Test" finished-at="2024-07-19T12:13:20 IST" duration-ms="9764">
      <class name="com.selenium_framework.RegUserTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.selenium_framework.RegUserTest@41e68d87]" started-at="2024-07-19T12:13:10 IST" name="setUp" finished-at="2024-07-19T12:13:13 IST" duration-ms="2601" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testRegUserPage()[pri:0, instance:com.selenium_framework.RegUserTest@41e68d87]" started-at="2024-07-19T12:13:13 IST" name="testRegUserPage" finished-at="2024-07-19T12:13:18 IST" duration-ms="5763" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ParaBank| Register for Free Online Account Access] but found [ParaBank | Register for Free Online Account Access]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ParaBank| Register for Free Online Account Access] but found [ParaBank | Register for Free Online Account Access]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.selenium_framework.RegUserTest.testRegUserPage(RegUserTest.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRegUserPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.selenium_framework.RegUserTest@41e68d87]" started-at="2024-07-19T12:13:18 IST" name="tearDown" finished-at="2024-07-19T12:13:20 IST" duration-ms="1338" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.selenium_framework.RegUserTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
